# Generated by Django 3.0.4 on 2020-04-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_transformation_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='scout.Transformation'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='scout.Recipe'),
        ),
        migrations.CreateModel(
            name='TempDataSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=2048)),
                ('sampling_technique', models.CharField(choices=[('random', 'Random'), ('stratified', 'Stratified'), ('top', 'Top')], default='top', max_length=64)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='scout.DataSource')),
            ],
        ),
    ]
