# Generated by Django 3.0.4 on 2021-02-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0009_auto_20210202_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='original_file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
