# Generated by Django 3.0.4 on 2021-02-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0011_auto_20210204_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='join_query',
        ),
        migrations.AddField(
            model_name='join',
            name='recipe_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_recipe_left', to='scout.Recipe'),
        ),
        migrations.AddField(
            model_name='join',
            name='recipe_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_recipe_right', to='scout.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='input_join',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_join', to='scout.Join'),
        ),
        migrations.AlterField(
            model_name='join',
            name='data_source_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_data_source_left', to='scout.DataSource'),
        ),
        migrations.AlterField(
            model_name='join',
            name='data_source_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_data_source_right', to='scout.DataSource'),
        ),
        migrations.AlterField(
            model_name='join',
            name='field_left',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='join',
            name='field_right',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='join',
            name='method',
            field=models.CharField(choices=[('inner', 'Inner'), ('outer', 'Outer'), ('left', 'Left'), ('right', 'Right'), ('cross', 'Cartesian product')], default='inner', max_length=512),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_input', to='scout.DataSource'),
        ),
    ]
