# Generated by Django 3.0.4 on 2021-02-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scout', '0015_auto_20210211_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='scout.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcefolder',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_source_folders', to='scout.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='scout.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='scout.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipefolder',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_folders', to='scout.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='scout.Project'),
            preserve_default=False,
        ),
    ]
