# Generated by Django 3.0.4 on 2020-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='name',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
    ]
