# Generated by Django 3.0.4 on 2021-01-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0005_recipe_sampling_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_output', to='scout.DataSource'),
        ),
    ]
