# Generated by Django 3.0.4 on 2021-01-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_auto_20210131_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='scout.DataSourceFolder')),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='scout.DataSourceFolder'),
        ),
    ]
