# Generated by Django 3.0.4 on 2021-02-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0008_auto_20210131_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scout.DataSourceFolder'),
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=1024)),
                ('original_file_name', models.CharField(max_length=1024)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scout.DataSource')),
            ],
        ),
    ]
